version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - chroma_data:/app/chroma_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    command: streamlit run src/app.py

volumes:
  chroma_data: